name: drainshield_app
description: "DrainShield mobile security app"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  url_launcher: 6.3.2
  reown_appkit: 1.8.3
  reown_core: 1.3.8
  reown_sign: 1.3.9
  path_provider: 2.1.5
  path: ^1.9.0
  url_launcher_android: 6.3.14

  in_app_purchase: ^3.2.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  audioplayers: ^6.1.0
  vibration: ^2.0.1
  workmanager: ^0.9.0
  connectivity_plus: ^7.0.0
  sqflite: ^2.3.0

dependency_overrides:
  sqflite: 2.3.3+1
  sqflite_android: 2.4.0
  url_launcher_android: 6.3.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/mascot/
    - assets/i18n/
    - assets/sounds/
    - secrets/moralis.json

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/logo/icon.png
  adaptive_icon_foreground: assets/logo/icon.png # Updated to use icon.png
  adaptive_icon_background: "#05070B"
  min_sdk_android: 24

flutter_native_splash: # Added flutter_native_splash configuration
  color: "#05070B"
  android_12:
    color: "#05070B"
  fullscreen: true