import 'dart:convert';
import 'dart:io';

void main() {
  final Map<String, Map<String, String>> proStrings = {
    'en': {
      'proValueProp': 'Enhanced protection for your wallets',
      'proMonitoringTitle': '24/7 Auto-Monitoring',
      'proMonitoringSub': 'Real-time threat detection',
      'proRevokeTitle': 'Batch Risk Revoke',
      'proRevokeSub': 'Clear all risks in one click',
      'proMultiWalletTitle': 'Multi-Wallet Support',
      'proMultiWalletSub': 'Protect up to 5 wallets',
      'proFirewallTitle': 'AI Firewall',
      'proFirewallSub': 'Blocking suspicious transactions',
      'proPriceSuffix': '/ per month',
      'proPriceCancelHint': 'Cancel anytime. Payment via Google Play.',
      'proUpgradeBtn': 'UPGRADE TO PRO',
      'proAccessBtn': 'PRO ACCESS',
    },
    'ru': {
      'proValueProp': '24/7 мониторинг безопасности кошелька',
      'proMonitoringTitle': '24/7 Авто-мониторинг',
      'proMonitoringSub': 'Обнаружение угроз в реальном времени',
      'proRevokeTitle': 'Пакетный отзыв рисков',
      'proRevokeSub': 'Очистка всех рисков в один клик',
      'proMultiWalletTitle': 'Поддержка нескольких кошельков',
      'proMultiWalletSub': 'Защита до 5 кошельков',
      'proFirewallTitle': 'AI Firewall',
      'proFirewallSub': 'Блокировка подозрительных транзакций',
      'proPriceSuffix': '/ в месяц',
      'proPriceCancelHint': 'Отмена в любое время. Оплата через Google Play.',
      'proUpgradeBtn': 'ПЕРЕЙТИ НА PRO',
      'proAccessBtn': 'ПРО ДОСТУП',
    },
    'de': {
      'proValueProp': 'Erweiterter Schutz für Ihre Wallets',
      'proMonitoringTitle': '24/7 Auto-Überwachung',
      'proMonitoringSub': 'Echtzeit-Bedrohungserkennung',
      'proRevokeTitle': 'Batch-Risiko-Widerruf',
      'proRevokeSub': 'Alle Risiken mit einem Klick löschen',
      'proMultiWalletTitle': 'Multi-Wallet-Unterstützung',
      'proMultiWalletSub': 'Bis zu 5 Wallets schützen',
      'proFirewallTitle': 'AI-Firewall',
      'proFirewallSub': 'Blockieren verdächtiger Transaktionen',
      'proPriceSuffix': '/ pro Monat',
      'proPriceCancelHint': 'Jederzeit kündbar. Zahlung über Google Play.',
      'proUpgradeBtn': 'AUF PRO UPGRADEN',
      'proAccessBtn': 'PRO-ZUGANG',
    },
    'fr': {
      'proValueProp': 'Protection améliorée pour vos portefeuilles',
      'proMonitoringTitle': 'Auto-surveillance 24/7',
      'proMonitoringSub': 'Détection des menaces en temps réel',
      'proRevokeTitle': 'Révocation des risques par lots',
      'proRevokeSub': 'Effacer tous les risques en un clic',
      'proMultiWalletTitle': 'Support multi-portefeuilles',
      'proMultiWalletSub': 'Protégez jusqu\'à 5 portefeuilles',
      'proFirewallTitle': 'Pare-feu IA',
      'proFirewallSub': 'Blocage des transactions suspectes',
      'proPriceSuffix': '/ par mois',
      'proPriceCancelHint': 'Annulation possible à tout moment. Paiement via Google Play.',
      'proUpgradeBtn': 'PASSER À PRO',
      'proAccessBtn': 'ACCÈS PRO',
    },
    'es': {
      'proValueProp': 'Protección mejorada para sus billeteras',
      'proMonitoringTitle': 'Auto-monitoreo 24/7',
      'proMonitoringSub': 'Detección de amenazas en tiempo real',
      'proRevokeTitle': 'Revocación de riesgos por lotes',
      'proRevokeSub': 'Borrar todos los riesgos en un clic',
      'proMultiWalletTitle': 'Soporte multi-billetera',
      'proMultiWalletSub': 'Proteja hasta 5 billeteras',
      'proFirewallTitle': 'Cortafuegos de IA',
      'proFirewallSub': 'Bloqueo de transacciones sospechosas',
      'proPriceSuffix': '/ por mes',
      'proPriceCancelHint': 'Cancele en cualquier momento. Pago a través de Google Play.',
      'proUpgradeBtn': 'MEJORAR A PRO',
      'proAccessBtn': 'ACCESO PRO',
    },
    'pt': {
      'proValueProp': 'Proteção aprimorada para suas carteiras',
      'proMonitoringTitle': 'Auto-monitorização 24/7',
      'proMonitoringSub': 'Deteção de ameaças em tempo real',
      'proRevokeTitle': 'Revogação de riscos em lote',
      'proRevokeSub': 'Eliminar todos os riscos num clique',
      'proMultiWalletTitle': 'Suporte multi-carteiras',
      'proMultiWalletSub': 'Proteja até 5 carteiras',
      'proFirewallTitle': 'Firewall de IA',
      'proFirewallSub': 'Bloqueio de transações suspeitas',
      'proPriceSuffix': '/ por mês',
      'proPriceCancelHint': 'Cancele a qualquer momento. Pagamento via Google Play.',
      'proUpgradeBtn': 'ATUALIZAR PARA PRO',
      'proAccessBtn': 'ACESSO PRO',
    },
    'tr': {
      'proValueProp': 'Cüzdanlarınız için gelişmiş koruma',
      'proMonitoringTitle': '24/7 Otomatik İzleme',
      'proMonitoringSub': 'Gerçek zamanlı tehdit algılama',
      'proRevokeTitle': 'Toplu Risk İptali',
      'proRevokeSub': 'Tüm riskleri tek tıkla temizle',
      'proMultiWalletTitle': 'Çoklu Cüzdan Desteği',
      'proMultiWalletSub': '5 cüzdana kadar koruyun',
      'proFirewallTitle': 'AI Güvenlik Duvarı',
      'proFirewallSub': 'Şüpheli işlemleri engelleme',
      'proPriceSuffix': '/ aylık',
      'proPriceCancelHint': 'İstediğiniz zaman iptal edin. Google Play üzerinden ödeme.',
      'proUpgradeBtn': 'PRO\'YA YÜKSELT',
      'proAccessBtn': 'PRO ERİŞİMİ',
    },
    'ar': {
      'proValueProp': 'حماية متقدمة لمحفظتك',
      'proMonitoringTitle': 'مراقبة تلقائية على مدار الساعة',
      'proMonitoringSub': 'كشف التهديدات في الوقت الفعلي',
      'proRevokeTitle': 'إلغاء المخاطر بالجملة',
      'proRevokeSub': 'مسح جميع المخاطر بنقرة واحدة',
      'proMultiWalletTitle': 'دعم محافظ متعددة',
      'proMultiWalletSub': 'حماية ما يصل إلى 5 محافظ',
      'proFirewallTitle': 'جدار حماية ذكاء اصطناعي',
      'proFirewallSub': 'حظر المعاملات المشبوهة',
      'proPriceSuffix': '/ شهر',
      'proPriceCancelHint': 'إلغاء في أي وقت. الدفع عبر Google Play.',
      'proUpgradeBtn': 'الترقية إلى برو',
      'proAccessBtn': 'وصول برو',
    },
    'zh': {
      'proValueProp': '为您的钱包提供增强保护',
      'proMonitoringTitle': '24/7 自动监控',
      'proMonitoringSub': '实时威胁检测',
      'proRevokeTitle': '批量风险撤销',
      'proRevokeSub': '一键清除所有风险',
      'proMultiWalletTitle': '多钱包支持',
      'proMultiWalletSub': '保护多达 5 个钱包',
      'proFirewallTitle': 'AI 防火墙',
      'proFirewallSub': '拦截可疑交易',
      'proPriceSuffix': '/ 每月',
      'proPriceCancelHint': '随时取消。通过 Google Play 付款。',
      'proUpgradeBtn': '升级到 PRO',
      'proAccessBtn': 'PRO 访问权限',
    },
    'hi': {
      'proValueProp': 'आपके वॉलेट के लिए बेहतर सुरक्षा',
      'proMonitoringTitle': '24/7 ऑटो-मॉनिटरिंग',
      'proMonitoringSub': 'वास्तविक समय में खतरे का पता लगाना',
      'proRevokeTitle': 'बैच जोखिम रद्दीकरण',
      'proRevokeSub': 'एक क्लिक में सभी जोखिमों को साफ करें',
      'proMultiWalletTitle': 'मल्टी-वॉलेट समर्थन',
      'proMultiWalletSub': '5 वॉलेट तक सुरक्षित रखें',
      'proFirewallTitle': 'AI फ़ायरवॉल',
      'proFirewallSub': 'संदिग्ध लेनदेन को रोकना',
      'proPriceSuffix': '/ प्रति माह',
      'proPriceCancelHint': 'कभी भी रद्द करें। Google Play के माध्यम से भुगतान।',
      'proUpgradeBtn': 'PRO में अपग्रेड करें',
      'proAccessBtn': 'PRO एक्सेस',
    },
    'ja': {
      'proValueProp': 'ウォレットの保護を強化',
      'proMonitoringTitle': '24時間365日の自動監視',
      'proMonitoringSub': 'リアルタイムの脅威検出',
      'proRevokeTitle': '一括リスク取り消し',
      'proRevokeSub': 'ワンクリックですべてのリスクをクリア',
      'proMultiWalletTitle': 'マルチウォレット対応',
      'proMultiWalletSub': '最大5つのウォレットを保護',
      'proFirewallTitle': 'AIファイアウォール',
      'proFirewallSub': '不審な取引をブロック',
      'proPriceSuffix': '/ 月',
      'proPriceCancelHint': 'いつでもキャンセル可能。Google Play経由での支払い。',
      'proUpgradeBtn': 'PROにアップグレード',
      'proAccessBtn': 'PROアクセス',
    },
    'ko': {
      'proValueProp': '지갑을 위한 강화된 보호',
      'proMonitoringTitle': '24/7 자동 모니터링',
      'proMonitoringSub': '실시간 위협 탐지',
      'proRevokeTitle': '일괄 리스크 철회',
      'proRevokeSub': '한 번의 클릭으로 모든 리스크 제거',
      'proMultiWalletTitle': '멀티 지갑 지원',
      'proMultiWalletSub': '최대 5개의 지갑 보호',
      'proFirewallTitle': 'AI 방화벽',
      'proFirewallSub': '의심스러운 거래 차단',
      'proPriceSuffix': '/ 월',
      'proPriceCancelHint': '언제든지 취소 가능. Google Play를 통해 결제.',
      'proUpgradeBtn': 'PRO로 업그레이드',
      'proAccessBtn': 'PRO 액세스',
    },
    'it': {
      'proValueProp': 'Protezione avanzata per i tuoi portafogli',
      'proMonitoringTitle': 'Auto-monitoraggio 24/7',
      'proMonitoringSub': 'Rilevamento minacce in tempo reale',
      'proRevokeTitle': 'Revoca dei rischi in batch',
      'proRevokeSub': 'Cancella tutti i rischi in un clic',
      'proMultiWalletTitle': 'Supporto multi-portafoglio',
      'proMultiWalletSub': 'Proteggi fino a 5 portafogli',
      'proFirewallTitle': 'Firewall AI',
      'proFirewallSub': 'Blocco delle transazioni sospette',
      'proPriceSuffix': '/ al mese',
      'proPriceCancelHint': 'Annulla in qualsiasi momento. Pagamento tramite Google Play.',
      'proUpgradeBtn': 'PASSA A PRO',
      'proAccessBtn': 'ACCESSO PRO',
    },
    'pl': {
      'proValueProp': 'Ulepszona ochrona Twoich portfeli',
      'proMonitoringTitle': 'Automatyczne monitorowanie 24/7',
      'proMonitoringSub': 'Wykrywanie zagrożeń w czasie rzeczywistym',
      'proRevokeTitle': 'Zbiorcze odwoływanie ryzyk',
      'proRevokeSub': 'Wyczyść wszystkie ryzyka jednym kliknięciem',
      'proMultiWalletTitle': 'Obsługa wielu portfeli',
      'proMultiWalletSub': 'Chroń do 5 portfeli',
      'proFirewallTitle': 'Firewall AI',
      'proFirewallSub': 'Blokowanie podejrzanych transakcji',
      'proPriceSuffix': '/ miesięcznie',
      'proPriceCancelHint': 'Anuluj w dowolnym momencie. Płatność przez Google Play.',
      'proUpgradeBtn': 'UPGRADE DO PRO',
      'proAccessBtn': 'DOSTĘP PRO',
    },
    'uk': {
      'proValueProp': 'Розширений захист для ваших гаманців',
      'proMonitoringTitle': '24/7 Авто-моніторинг',
      'proMonitoringSub': 'Виявлення загроз у реальному часі',
      'proRevokeTitle': 'Пакетне відкликання ризиків',
      'proRevokeSub': 'Очищення всіх ризиків в один клік',
      'proMultiWalletTitle': 'Підтримка кількох гаманців',
      'proMultiWalletSub': 'Захист до 5 гаманців',
      'proFirewallTitle': 'AI Firewall',
      'proFirewallSub': 'Блокування підозрілих транзакцій',
      'proPriceSuffix': '/ на місяць',
      'proPriceCancelHint': 'Скасування в будь-який час. Оплата через Google Play.',
      'proUpgradeBtn': 'ПЕРЕЙТИ НА PRO',
      'proAccessBtn': 'ПРО ДОСТУП',
    },
    'id': {
      'proValueProp': 'Perlindungan yang ditingkatkan untuk dompet Anda',
      'proMonitoringTitle': 'Pemantauan Otomatis 24/7',
      'proMonitoringSub': 'Deteksi ancaman waktu nyata',
      'proRevokeTitle': 'Pencabutan Risiko Batch',
      'proRevokeSub': 'Hapus semua risiko dalam satu klik',
      'proMultiWalletTitle': 'Dukungan Multi-Dompet',
      'proMultiWalletSub': 'Lindungi hingga 5 dompet',
      'proFirewallTitle': 'Firewall AI',
      'proFirewallSub': 'Pemblokiran transaksi mencurigakan',
      'proPriceSuffix': '/ per bulan',
      'proPriceCancelHint': 'Batalkan kapan saja. Pembayaran melalui Google Play.',
      'proUpgradeBtn': 'TINGKATKAN KE PRO',
      'proAccessBtn': 'AKSES PRO',
    },
    'vi': {
      'proValueProp': 'Bảo vệ nâng cao cho ví của bạn',
      'proMonitoringTitle': 'Tự động giám sát 24/7',
      'proMonitoringSub': 'Phát hiện mối đe dọa thời gian thực',
      'proRevokeTitle': 'Thu hồi rủi ro hàng loạt',
      'proRevokeSub': 'Xóa tất cả rủi ro trong một lần nhấp',
      'proMultiWalletTitle': 'Hỗ trợ đa ví',
      'proMultiWalletSub': 'Bảo vệ tối đa 5 ví',
      'proFirewallTitle': 'Tường lửa AI',
      'proFirewallSub': 'Chặn các giao dịch đáng ngờ',
      'proPriceSuffix': '/ tháng',
      'proPriceCancelHint': 'Hủy bất kỳ lúc nào. Thanh toán qua Google Play.',
      'proUpgradeBtn': 'NÂNG CẤP LÊN PRO',
      'proAccessBtn': 'TRUY CẬP PRO',
    },
  };

  proStrings.forEach((lang, strings) {
    final file = File('assets/i18n/$lang.json');
    if (file.existsSync()) {
      final content = json.decode(file.readAsStringSync());
      strings.forEach((key, value) {
        content[key] = value;
      });
      
      const encoder = JsonEncoder.withIndent('    ');
      file.writeAsStringSync(encoder.convert(content));
      print('Updated PRO strings in assets/i18n/$lang.json');
    }
  });
}
